# Generated by Django 5.0.4 on 2024-05-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0015_configuracion'),
        ('enbalde', '0016_alter_venta_total'),
    ]

    operations = [
    ]
