name: Android CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      working-directory: app
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: app
      run: mkdir -p build && ./gradlew build --stacktrace --info

    - name: Test
      working-directory: app
      run: mkdir -p build && ./gradlew test

